# Generated by Django 4.1 on 2023-12-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='adm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adm', to=settings.AUTH_USER_MODEL),
        ),
    ]
