# Generated by Django 4.1 on 2023-12-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='chat_chat_unique',
        ),
    ]
