# Generated by Django 4.1 on 2023-12-20 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_chat_chat_chat_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='util_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_util_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='util_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_util_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('util_1', 'util_2'), name='chat_chat_unique'),
        ),
    ]
