# Generated by Django 4.1 on 2024-01-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('Create', 'create'), ('Join', 'join'), ('Left', 'left'), ('Normal', 'normal')], default='normal', max_length=6),
        ),
    ]
