# Generated by Django 4.1 on 2023-12-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_chat_util_1_alter_chat_util_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
