# Generated by Django 4.1 on 2024-01-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('Info', 'info'), ('Create', 'create'), ('Join', 'join'), ('Left', 'left'), ('Normal', 'normal')], default='normal', max_length=6),
        ),
    ]
