# Generated by Django 4.1 on 2024-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('Delivered', 'delivered'), ('Received', 'received')], default='sent', max_length=9),
        ),
    ]
