# Generated by Django 4.1 on 2023-12-21 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_message_util'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='chat_chat_unique',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='util_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='util_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='utilisateurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
