# Generated by Django 4.1 on 2024-01-09 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 9, 22, 14, 335027, tzinfo=datetime.timezone.utc)),
        ),
    ]
