# Generated by Django 4.1 on 2023-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_chat_chat_unique_remove_chat_util_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='nom_chat',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
