# Generated by Django 4.1 on 2024-01-09 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 9, 24, 21, 537341, tzinfo=datetime.timezone.utc)),
        ),
    ]
