# Generated by Django 4.1 on 2023-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_nom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='groupe',
            field=models.BooleanField(default=False),
        ),
    ]
