# Generated by Django 4.1 on 2024-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=(2024, 1, 9, 10, 29, 14, 1, 9, 0)),
        ),
    ]
