# Generated by Django 4.1 on 2023-12-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_groupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='nom_chat',
            new_name='nom_groupe',
        ),
    ]
